### ISSUE TITLE
Release包还是会崩溃的啊

### ISSUE THREAD

**Issue by brandlee** [ltttttttttttt/ComposeViews#37]

**Comment by ltttttttttttt** [comment]
哪个地方?日志贴一下

**Comment by brandlee** [comment]
FATAL EXCEPTION: main
                                                                                                    Process: com.quickwis.fapiaohezi, PID: 28128
                                                                                                    java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:594)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)
                                                                                                    Caused by: java.lang.reflect.InvocationTargetException
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013) 
                                                                                                    Caused by: java.lang.NoSuchMethodException: androidx.compose.ui.platform.g0.getLocalContext []
                                                                                                    	at java.lang.Class.getMethod(Class.java:2103)
                                                                                                    	at java.lang.Class.getMethod(Class.java:1724)
                                                                                                    	at f5.a.e(Unknown Source:9)
                                                                                                    	at f5.a.b(Unknown Source:0)
                                                                                                    	at f5.a$a.a(Unknown Source:2)
                                                                                                    	at f5.a$a.F(Unknown Source:0)
                                                                                                    	at d7.u.getValue(Unknown Source:20)
                                                                                                    	at f5.a.h(Unknown Source:2)
                                                                                                    	at f5.a.d(Unknown Source:18)
                                                                                                    	at f5.a.l(Unknown Source:32)
                                                                                                    	at d5.a.a(Unknown Source:324)
                                                                                                    	at c5.h$a.a(Unknown Source:31)
                                                                                                    	at c5.h$a.Q(Unknown Source:10)
                                                                                                    	at k0.b.b(Unknown Source:49)
                                                                                                    	at k0.b.Q(Unknown Source:8)
                                                                                                    	at c5.c.a(Unknown Source:749)
                                                                                                    	at c5.h$b.a(Unknown Source:76)
                                                                                                    	at c5.h$b.A0(Unknown Source:8)
                                                                                                    	at k0.b.a(Unknown Source:49)
                                                                                                    	at k0.b.A0(Unknown Source:8)
                                                                                                    	at c5.c.a(Unknown Source:733)
                                                                                                    	at c5.h.a(Unknown Source:184)

**Comment by brandlee** [comment]
com.lt.compose_views.refresh_layout.VerticalRefreshableLayoutKt -> c5.h:
    void VerticalRefreshableLayout(com.lt.compose_views.refresh_layout.RefreshLayoutState,com.lt.compose_views.refresh_layout.RefreshLayoutState,androidx.compose.ui.Modifier,kotlin.jvm.functions.Function3,boolean,kotlin.jvm.functions.Function3,kotlin.jvm.functions.Function2,androidx.compose.runtime.Composer,int,int) -> a

**Comment by ltttttttttttt** [comment]
你加混淆的配置了吗?在readme最下面

**Comment by ltttttttttttt** [comment]
晚点我查查什么原因哈,这会有点事

**Comment by ltttttttttttt** [comment]
你引用这个库试一下,看看还有没有问题了
"androidx.compose.material:animation:$composeVersion"

**Comment by brandlee** [comment]
我定位到问题了，应该就是我混淆的时候对Parcelable有点问题，感谢啦！
然后还想请教一个问题，DateSelector为啥不支持字体和字号的设置啊，我看ValueSelector里面都已经是支持了的。

**Comment by ltttttttttttt** [comment]
ok,那我给DateSelector加一下参数

**Comment by ltttttttttttt** [comment]
新版本1.3.7.1
