### ISSUE TITLE
升级到Compose bom 2024.01.00后 dataselector报错

### ISSUE THREAD

**Issue by gangoogle** [ltttttttttttt/ComposeViews#82]
*Target (Android,):*

*ComposeViews versions:* 2024.01.00

*Sample code*

`java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/compose/foundation/OverscrollConfigurationKt;
                                                                    	at com.lt.compose_views.value_selector.ValueSelectorCompositionLocalProvider_androidKt.ValueSelectorCompositionLocalProvider(ValueSelectorCompositionLocalProvider.android.kt:28)
                                                                    	at com.lt.compose_views.value_selector.ValueSelectorKt.ValueSelector-l5lsQBU(ValueSelector.kt:145)
                                                                    	at com.lt.compose_views.value_selector.date_selector.DateSelectorKt.DateSelector-eRCXkDE(DateSelector.kt:76)
                                                                    	at com.rms.field_operation.ui.schedule.YardScheduleDialog$DateSelect$2$1.invoke(YardScheduleDialog.kt:270)
                                                                    	at com.rms.field_operation.ui.schedule.YardScheduleDialog$DateSelect$2$1.invoke(YardScheduleDialog.kt:252)
                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:118)
                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
                                                                    	at androidx.compose.material3.CardKt$Card$1.invoke(Card.kt:806)
                                                                    	at androidx.compose.material3.CardKt$Card$1.invoke(Card.kt:92)
                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:109)
                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
                                                                    	at androidx.compose.material3.SurfaceKt$Surface$1.invoke(Surface.kt:132)
                                                                    	at androidx.compose.material3.SurfaceKt$Surface$1.invoke(Surface.kt:114)
                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:109)
                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
                                                                    	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)
                                                                    	at androidx.compose.material3.SurfaceKt.Surface-T9BRK9s(Surface.kt:111)
                                                                    	at androidx.compose.material3.CardKt.Card(Card.kt:84)
                                                                    	at com.rms.field_operation.ui.schedule.YardScheduleDialog$DateSelect$2.invoke(YardScheduleDialog.kt:247)
                                                                    	at com.rms.field_operation.ui.schedule.YardScheduleDialog$DateSelect$2.invoke(YardScheduleDialog.kt:246)
                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:109)
                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
                                                                    	at androidx.compose.ui.window.AndroidDialog_androidKt$Dialog$dialog$1$1$1$2.invoke(AndroidDialog.android.kt:177)
                                                                    	at androidx.compose.ui.window.AndroidDialog_androidKt$Dialog$dialog$1$1$1$2.invoke(AndroidDialog.android.kt:176)
                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:109)
                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
                                                                    	at androidx.compose.ui.window.AndroidDialog_androidKt.DialogLayout(AndroidDialog.android.kt:505)
                                                                    	at androidx.compose.ui.window.AndroidDialog_androidKt.access$DialogLayout(AndroidDialog.android.kt:1)
                                                                    	at androidx.compose.ui.window.AndroidDialog_androidKt$Dialog$dialog$1$1$1.invoke(AndroidDialog.android.kt:174)
                                                                    	at androidx.compose.ui.window.AndroidDialog_androidKt$Dialog$dialog$1$1$1.invoke(AndroidDialog.android.kt:171)
                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:109)
                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
                                                                    	at androidx.compose.ui.window.DialogLayout.Content(AndroidDialog.android.kt:270)
                                                                    	at androidx.compose.ui.platform.AbstractComposeView$ensureCompositionCreated$1.invoke(ComposeView.android.kt:252)
                                                                    	at androidx.compose.ui.platform.AbstractComposeView$ensureCompositionCreated$1.invoke(ComposeView.android.kt:251)
                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:109)
                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
                                                                    	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)
                                                                    	at androidx.compose.ui.platform.CompositionLocalsKt.ProvideCommonCompositionLocals(CompositionLocals.kt:186)
09:09:14.593  2554-2554  CrashReport    com.rms.field_operation  E  	at androidx.compose.ui.platform.AndroidCompositionLocals_androidKt$ProvideAndroidCompositionLocals$3.invoke(AndroidCompositionLocals.android.kt:119)
                                                                    	at androidx.compose.ui.platform.AndroidCompositionLocals_androidKt$ProvideAndroidCompositionLocals$3.invoke(AndroidCompositionLocals.android.kt:118)
                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:109)
                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
                                                                    	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)
                                                                    	at androidx.compose.ui.platform.AndroidCompositionLocals_androidKt.ProvideAndroidCompositionLocals(AndroidCompositionLocals.android.kt:110)
                                                                    	at androidx.compose.ui.platform.WrappedComposition$setContent$1$1$2.invoke(Wrapper.android.kt:139)
                                                                    	at androidx.compose.ui.platform.WrappedComposition$setContent$1$1$2.invoke(Wrapper.android.kt:138)
                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:109)
                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
                                                                    	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:248)
                                                                    	at androidx.compose.ui.platform.WrappedComposition$setContent$1$1.invoke(Wrapper.android.kt:138)
                                                                    	at androidx.compose.ui.platform.WrappedComposition$setContent$1$1.invoke(Wrapper.android.kt:123)
                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:109)
                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
                                                                    	at androidx.compose.runtime.ActualJvm_jvmKt.invokeComposable(ActualJvm.jvm.kt:90)
                                                                    	at androidx.compose.runtime.ComposerImpl.doCompose(Composer.kt:3302)
                                                                    	at androidx.compose.runtime.ComposerImpl.composeContent$runtime_release(Composer.kt:3235)
                                                                    	at androidx.compose.runtime.CompositionImpl.composeContent(Composition.kt:723)
                                                                    	at androidx.compose.runtime.Recomposer.composeInitial$runtime_release(Recomposer.kt:1071)
                                                                    	at androidx.compose.runtime.ComposerImpl$CompositionContextImpl.composeInitial$runtime_release(Composer.kt:3599)
                                                                    	at androidx.compose.runtime.ComposerImpl$CompositionContextImpl.composeInitial$runtime_release(Composer.kt:3599)
                                                                    	at androidx.compose.runtime.ComposerImpl$CompositionContextImpl.composeInitial$runtime_release(Composer.kt:3599)
                                                                    	at androidx.compose.runtime.CompositionImpl.composeInitial(Composition.kt:631)
                                                                    	at androidx.compose.runtime.CompositionImpl.setContent(Composition.kt:617)
                                                                    	at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke(Wrapper.android.kt:123)
                                                                    	at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke(Wrapper.android.kt:114)
                                                                    	at androidx.compose.ui.platform.AndroidComposeView.setOnViewTreeOwnersAvailable(AndroidComposeView.android.kt:1289)
                                                                    	at androidx.compose.ui.platform.WrappedComposition.setContent(Wrapper.android.kt:114)
                                                                    	at androidx.compose.ui.platform.WrappedComposition.onStateChanged(Wrapper.android.kt:164)
                                                                    	at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.kt:314)
                                                                    	at androidx.lifecycle.LifecycleRegistry.addObserver(LifecycleRegistry.kt:192)
                                                                    	at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke(Wrapper.android.kt:121)
                                                                    	at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke(Wrapper.android.kt:114)
                                                                    	at androidx.compose.ui.platform.AndroidComposeView.onAttachedToWindow(AndroidComposeView.android.kt:1364)
                                                                    	at android.view.View.dispatchAttachedToWindow(View.java:21472)
                                                                    	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3532)
                                                                    	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3539)
                                                                    	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3539)
                                                                    	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3539)
                                                                    	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3539)
                                                                    	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3130)
09:09:14.593  2554-2554  CrashReport    com.rms.field_operation  E  	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2622)
                                                                    	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9644)
                                                                    	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1494)
                                                                    	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1502)
                                                                    	at android.view.Choreographer.doCallbacks(Choreographer.java:1117)
                                                                    	at android.view.Choreographer.doFrame(Choreographer.java:1034)
                                                                    	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1470)
                                                                    	at android.os.Handler.handleCallback(Handler.java:942)
                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                    	at android.os.Looper.loopOnce(Looper.java:211)
                                                                    	at android.os.Looper.loop(Looper.java:300)
                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8432)
                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:560)
                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)
                                                                    Caused by: java.lang.ClassNotFoundException: Didn't find class "androidx.compose.foundation.OverscrollConfigurationKt" on path: DexPathList[[dex file "InMemoryDexFile[cookie=[0, -5476376660925206080]]", dex file "/data/data/com.rms.field_operation/code_cache/.overlay/base.apk/classes18.dex", zip file "/data/app/~~XCMRt4Ayv2G0-QTl8DqZpg==/com.rms.field_operation-zJhtto2h-Z9WubkLTonJqA==/base.apk"],nativeLibraryDirectories=[/data/app/~~XCMRt4Ayv2G0-QTl8DqZpg==/com.rms.field_operation-zJhtto2h-Z9WubkLTonJqA==/lib/arm64, /data/app/~~XCMRt4Ayv2G0-QTl8DqZpg==/com.rms.field_operation-zJhtto2h-Z9WubkLTonJqA==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]
                                                                    	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:259)
                                                                    	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
                                                                    	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                                                                    	... 96 more`

**Comment by ltttttttttttt** [comment]
回头我适配下compose multiplatform 1.6.0-beta01

**Comment by ltttttttttttt** [comment]
版本:1.6.0-beta02.beta1
后续compose multiplatform出正式版了我再发正式版
